name: stiknes
description: "A new Flutter project."
version: 1.0.0+1
publish_to: 'none'  # Prevent accidental publishing to pub.dev

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_markdown: ^0.6.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - .env